src/core/gatekeeper/urls.py
from django.conf.urls import patterns, url
 
from gatekeeper import views 
 
urlpatterns = patterns('',
    # Absolute definitions go first
    url(r'^login', views.login, name='login'),
	url(r'^doLogin', views.doLogin, name='doLogin'),
    url(r'^logout', views.doLogout, name='logout'),
    url(r'^edit', views.edit, name='edit'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    
)

src/core/web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	url(r'^account/', include('gatekeeper.urls', namespace="gatekeeper")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'', include('pages.urls', namespace="pages")),
	
    # Application Specific definitions
    #url(r'^i/', include('personal.urls', namespace="personal")),	
)

src/core/gatekeeper/models.py
from django.db import models

# Create your models here.

src/core/gatekeeper/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import logout

def login(request):
    context = {'page_sidebar': 'false'}
    return render(request, 'gatekeeper/login.html', context)

def doLogin(request):
    try:
        if request.POST['newuser']:
            # Create user and log in automatically
            user = User.objects.create_user(request.POST['username'], request.POST['username'], request.POST['password'])
            user.save()
            
            messages.success(request, "Thanks for signing up! Hope you have a good time around here!")
            return HttpResponseRedirect(reverse('gatekeeper:dashboard'))
        else:
            # Login existing user
            user = authenticate(username=request.POST['username'], password=request.POST['password'])
            if user is not None:
                # the password verified for the user
                if user.is_active:
                    messages.success(request, "Thanks for returning!")
                    
                    # Redirect to Dashboard
                    return HttpResponseRedirect(reverse('gatekeeper:dashboard'))    
                else:
                    messages.success(request, "The password is valid, but the account has been disabled!")
                    return HttpResponseRedirect(reverse('gatekeeper:login'))
            else:
                # the authentication system was unable to verify the username and password
                messages.success(request, "Username and password are incorrect.")
                return HttpResponseRedirect(reverse('gatekeeper:login'))
            
    except (KeyError, any):
        messages.error(request, "We don't really understand the entered information. Can you please retry?")
        return HttpResponseRedirect(reverse('gatekeeper:login'))
        
def doLogout(request):
    # Clear session and redirect to home
    logout(request)
    return HttpResponseRedirect(reverse('pages:index'))
        
def edit(request):
    context = {'page_sidebar': 'false'}
    return render(request, 'gatekeeper/edit.html', context)
    
def dashboard(request):
    context = {'page_sidebar': 'false'}
    return render(request, 'gatekeeper/dashboard.html', context)

src/core/gatekeeper/templates/gatekeeper/dashboard.html
{% extends "base-pages.html" %}

{% block page_title %}
	Dashboard
{% endblock %}

{% block page_name %}
    Dashboard
{% endblock %}

{% block page_content %}
	
	<div class="large-12 columns">	
		<p>Ok, All the usual code goes in here!</p>
	</div>
	
{% endblock %}

src/core/gatekeeper/templates/gatekeeper/edit.html
{% extends "base-pages.html" %}

{% block page_title %}
	Edit Profile
{% endblock %}

{% block page_name %}
	Edit Profile
{% endblock %}

{% block page_content %}
	
	<div class="large-12 columns">	
		<p>Ok, All the usual code goes in here!</p>
	</div>
	
{% endblock %}

src/core/gatekeeper/templates/gatekeeper/login.html
{% extends "base-pages.html" %}

{% block page_title %}
	Login
{% endblock %}

{% block page_name %}
	Login
{% endblock %}

{% block page_content %}
	<div class="large-6 large-centered columns">	
		<form action="{% url 'gatekeeper:doLogin' %}" method="post">
			{% csrf_token %}
			<div class="large-12 colums">
				<label>
					<input type="checkbox" name="newuser" id="newuser"/> I don't have an account as yet!
				</label>
				<label id="lbSignUp">No worries! We'll sign you up. Just key-in the below information</label></br></br>
			</div>
			<div class="email-field">
				<label>Email:
					<input type="email" name="username" required placeholder="user@name.com"/></br></br>
				</label>
			</div>
			<label>Password:
				<input type="password" name="password" placeholder="" /></br></br>
			</label>
			<input id="btnLogin" class="button" type="submit" value="Login" />
			<input id="btnSignUp" class="button" type="submit" value="Sign me in" />
		</form>
	</div>
	
	<script language="javascript">
	
		$('#lbSignUp').hide();
		$('#btnSignUp').hide();
	
		$('#newuser').change(
		function(){
			if ($(this).is(':checked')) {
				$('#btnLogin').hide();
				$('#lbSignUp').show();
				$('#btnSignUp').show();
			} else {
				$('#btnLogin').show();
				$('#lbSignUp').hide();
				$('#btnSignUp').hide();
			}
		});
		
	</script>
	
{% endblock %}