src/core/allauth/account/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    url(r"^signup/$", views.signup, name="account_signup"),
    url(r"^login/$", views.login, name="account_login"),
    url(r"^logout/$", views.logout, name="account_logout"),

    url(r"^password/change/$", views.password_change,
        name="account_change_password"),
    url(r"^password/set/$", views.password_set, name="account_set_password"),

    url(r"^inactive/$", views.account_inactive, name="account_inactive"),

    # E-mail
    url(r"^email/$", views.email, name="account_email"),
    url(r"^confirm-email/$", views.email_verification_sent,
        name="account_email_verification_sent"),
    url(r"^confirm-email/(?P<key>\w+)/$", views.confirm_email,
        name="account_confirm_email"),

    # password reset
    url(r"^password/reset/$", views.password_reset,
        name="account_reset_password"),
    url(r"^password/reset/done/$", views.password_reset_done,
        name="account_reset_password_done"),
    url(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        views.password_reset_from_key,
        name="account_reset_password_from_key"),
    url(r"^password/reset/key/done/$", views.password_reset_from_key_done,
        name="account_reset_password_from_key_done"),
]

src/core/allauth/socialaccount/providers/amazon/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import AmazonProvider

urlpatterns = default_urlpatterns(AmazonProvider)

src/core/allauth/socialaccount/providers/baidu/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BaiduProvider

urlpatterns = default_urlpatterns(BaiduProvider)

src/core/allauth/socialaccount/providers/bitly/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import BitlyProvider

urlpatterns = default_urlpatterns(BitlyProvider)

src/core/allauth/socialaccount/providers/douban/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import DoubanProvider

urlpatterns = default_urlpatterns(DoubanProvider)

src/core/allauth/socialaccount/providers/edmodo/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import EdmodoProvider

urlpatterns = default_urlpatterns(EdmodoProvider)

src/core/allauth/socialaccount/providers/feedly/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import FeedlyProvider

urlpatterns = default_urlpatterns(FeedlyProvider)

src/core/allauth/socialaccount/providers/fxa/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import FirefoxAccountsProvider

urlpatterns = default_urlpatterns(FirefoxAccountsProvider)

src/core/allauth/socialaccount/providers/hubic/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import HubicProvider

urlpatterns = default_urlpatterns(HubicProvider)

src/core/allauth/socialaccount/providers/oauth/urls.py
from django.conf.urls import url, include
from allauth.utils import import_attribute


def default_urlpatterns(provider):

    login_view = import_attribute(provider.package + '.views.oauth_login')
    callback_view = import_attribute(provider.package + '.views.oauth_callback')

    urlpatterns = [
        url('^login/$', login_view, name=provider.id + "_login"),
        url('^login/callback/$', callback_view, name=provider.id + "_callback"),
    ]

    return [url('^' + provider.id + '/', include(urlpatterns))]

src/core/allauth/socialaccount/providers/orcid/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import OrcidProvider

urlpatterns = default_urlpatterns(OrcidProvider)

src/core/allauth/socialaccount/providers/vimeo/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns
from .provider import VimeoProvider

urlpatterns = default_urlpatterns(VimeoProvider)

src/core/allauth/socialaccount/providers/vk/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import VKProvider

urlpatterns = default_urlpatterns(VKProvider)

src/core/allauth/socialaccount/providers/weibo/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import WeiboProvider

urlpatterns = default_urlpatterns(WeiboProvider)

src/core/allauth/socialaccount/providers/xing/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns
from .provider import XingProvider

urlpatterns = default_urlpatterns(XingProvider)

src/core/allauth/socialaccount/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^login/cancelled/$', views.login_cancelled,
        name='socialaccount_login_cancelled'),
    url('^login/error/$', views.login_error, name='socialaccount_login_error'),
    url('^signup/$', views.signup, name='socialaccount_signup'),
    url('^connections/$', views.connections, name='socialaccount_connections')
]

src/core/allauth/urls.py
from django.conf.urls import url, include

try:
    import importlib
except ImportError:
    from django.utils import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = [url('^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url('^social/', include('allauth.socialaccount.urls'))]

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.package + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

src/core/blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
	url(r'^(?P<post_slug>[a-z]+)/$', views.post, name='post'),
    url(r'^$', views.index, name='index'),
)

src/core/gatekeeper/urls.py
from django.conf.urls import patterns, url
 
from gatekeeper import views 
 
urlpatterns = patterns('',
    # Absolute definitions go first
    url(r'^login', views.login, name='login'),
	url(r'^doLogin', views.doLogin, name='doLogin'),
    url(r'^logout', views.doLogout, name='logout'),
    url(r'^edit', views.edit, name='edit'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    
)

src/core/pages/urls.py
from django.conf.urls import patterns, url
 
from pages import views 
 
urlpatterns = patterns('',
    # Absolute definitions go first
    url(r'^$', views.index, name='index'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^message', views.message, name='message'),
    url(r'^(?P<page_slug>[a-z]+)/$', views.page, name='page'),
)

src/core/web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	url(r'^account/', include('gatekeeper.urls', namespace="gatekeeper")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'', include('pages.urls', namespace="pages")),
	
    # Application Specific definitions
    #url(r'^i/', include('personal.urls', namespace="personal")),	
)

src/core/pages/templates/pages/contact.html
{% extends "base-pages.html" %}

{% block page_title %}
	{{content.page_name}}
{% endblock %}

{% block page_name %}
	{{content.page_name}}
{% endblock %}

{% block page_content %}
	{% if messages %}
	</br></br>
	<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	</br></br>
		<p>{{content.page_content|safe}}</p>
	</br></br>
	<hr>
	</br>
	<h3>Leave us a note</h3>
	<form action="{% url 'pages:message' %}" method="post">
		{% csrf_token %}
		<p>{{form.as_p }}</p>
		<input type="submit" value="Submit" class="button"/>
	</form>
{% endblock %}

src/core/pages/templates/pages/index.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}
	Dawn::Home
{% endblock %}

{% block content %}

	<div class="large-12 columns large-tile text-center">
		
			<!-- Slider -->
			<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.4.1/slick.css"/>
			<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.4.1/slick-theme.css"/>
			
			<div class="home-slider text-center" data-slick='{"slidesToShow": 1, "slidesToScroll": 1, "centerMode": true, "autoplay": true, "dots": true, "arrows": false, "variableWidth": false}'>
				<div class="large-12 columns text-center">
					</br>
					<p>Combines the power of <h1>Django / Python 3</h1> and the <h1>Foundation Framework</h1> to in a boilerplate that serves as a base for creating powerful backends with appealing interfaces</p>
				</div>
				<div class="large-12 columns text-center">
					</br>
					<p>End-to-end development workflows defined for <h1>Vagrant</h1>and deployment workflows on the latest Ubuntu LTS with integrations to <h1>Apache (2.4) / ModWSGI</h1>
					Ensuring all your requirements and dependencies for development and deployment</br> are enclosed in one package</p>
				</div>
				<div class="large-12 columns text-center">
					</br>
					<p>Support for, <h1>Auth and User Management</h1>Integrates django-allauth, with authentication, account management and social integration. 
					<h1>Static Pages and Blog</h1>
					With handlers for form submissions like 'contact', with an in-house blogging engine
					
				</div>
			</div>
			
			<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.4.1/slick.min.js"></script>
			<!-- End Slider -->
		
	</div>
	<div class="row">
		<div class="large-12 columns text-center">
			<div class="large-12 columns panel text-center">
				<p>Get it now - <a href="https://bitbucket.org/immanuelnoel/dawn-django-boilerplate" target="_blank">https://bitbucket.org/immanuelnoel/dawn-django-boilerplate</a></p>
			</div>
			</br></br>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</br></br>
			<hr>
			</br>
			<div class="large-6 columns">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
			<div class="large-6 columns">	
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
		</div>
	</div>

		
{% endblock %}

src/core/pages/templates/pages/page.html
{% extends "base-pages.html" %}

{% block page_title %}
	{{content.page_name}}
{% endblock %}

{% block page_name %}
	{{content.page_name}}
{% endblock %}

{% block page_content %}
	{{content.page_content|safe}}
{% endblock %}

src/core/templates/base-blog.html
{% extends "base.html" %}

{% block title %}
	{% block blog_title %}{% endblock %} :: Dawn
{% endblock %}

{% block content %}
	
	<div class="large-12 columns standard-tile">
		<div class="row">
			</br>
			<h4>{% block blog_name %}{% endblock %}</h4>
		</div>
	</div>
	<div class="row">
		</br></br>
		<div class="large-12 columns">
			<div class="large-9 columns">
				<p>
					{% block blog_content %}
					{% endblock %}
				</p>
			</div>
			<div class="large-3 columns">	
				<p>Spacing out for the sidebar</p>
			</div>
		</div>
	</div>
{% endblock %}

src/core/templates/base-pages.html
{% extends "base.html" %}

{% block title %}
	Dawn :: {% block page_title %}{% endblock %}
{% endblock %}

{% block content %}
	
	<div class="large-12 columns standard-tile">
		<div class="row">
			</br>
			<h4>{% block page_name %}{% endblock %}</h4>
		</div>
	</div>
	<div class="row">
		</br></br>
		<div class="large-12 columns">
			{% ifequal page_sidebar "true" %}
				<div class="large-9 columns">
			{% else %}
				<div class="large-12 columns">
			{% endifequal %}
					<p>
						{% include "messages.html" %}
						{% block page_content %}
						{% endblock %}
					</p>
				</div>
				
			{% ifequal page_sidebar "true" %}
			<!-- Sidebar included -->
				<div class="large-3 columns">	
					{% block side_bar %}
					{% endblock %}
				</div>
			{% endifequal %}
			
		</div>
	</div>
{% endblock %}

src/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	
	<!-- LIBRARIES -->
    <link rel="stylesheet" href="{% static '/static/foundation/css/foundation.css' %}" />
    <script src="{% static '/static/foundation/js/vendor/modernizr.js' %}"></script>
	<script src="{% static '/static/foundation/js/vendor/jquery.js' %}"></script>
    <script src="{% static '/static/foundation/js/foundation.min.js' %}"></script>
	<!-- END LIBRARIES -->
	
	<!-- CUSTOM SETS -->
	<link href="{% static '/static/css/style.css' %}" rel="stylesheet" type="text/css">
	<!-- END CUSTOM SETS -->
	
	<title>{% block title %}Dawn{% endblock %}</title>
</head>

<body>

	<script language="javascript">
		$(document).ready(function(){
			//alert("JQuery is HERE!");
		});
	</script>
		
	{% include "header.html" %}
		
	{% block content %}{% endblock %}
	
	{% include "footer.html" %}
	
	<!-- LIBRARIES -->
	<script>
      $(document).foundation();
    </script>
	<!-- END LIBRARIES -->
	
</body>
</html>

src/core/templates/footer.html
<div class="small-12 columns footer">
	<hr>
	<div class="small-12 columns footer text-center">
		<p><a href="{% url 'pages:page' 'about' %}">About</a> | <a href="{% url 'pages:page' 'work' %}">Work</a> | <a href="{% url 'blog:index' %}">Blog</a> | <a href="{% url 'pages:page' 'contact' %}">Contact</a></p>
	</div>
	<div class="small-12 columns footer">
		<div class="small-9 columns footer">
			<p>{% block footer %}<a href="http://immanuelnoel.com" target="_blank">immanuelnoel.com</a> (c) 2015 | <a href="https://bitbucket.org/immanuelnoel/dawn-django-boilerplate" target="_blank">Download DAWN</a>{% endblock %}</p>
		</div>
		<div class="small-3 columns footer text-right">
			<p><a href="http://facebook.com" target="_blank">Facebook</a> | <a href="http://twitter.com" target="_blank">Twitter</a> | <a href="mailto:someone@mail.com" target="_blank">Email</a></p>
		</div>
	</div>
</div>

src/core/templates/header.html
<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name">
				<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
				<h1><a href="/" style="font-family: 'Questrial', sans-serif; font-size:40px">Dawn</a></h1>
			</li>
			<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		</ul>

		<section class="top-bar-section">
		<!-- Right Nav Section -->
		<ul class="right">
			<!--- if logged in --->
			<li><a href="{% url 'gatekeeper:dashboard' %}">Dashboard</a></li>
			<li><a href="{% url 'gatekeeper:edit' %}">Edit</a></li>
			<li><a href="{% url 'gatekeeper:logout' %}">Logout</a></li>
		
			<!--- if logged out --->
			<li><a href="{% url 'gatekeeper:login' %}">Login / Sign Up</a></li>
			<li><a href="{% url 'blog:index' %}">Blog</a></li>
		
		</ul>
	  </section>
	</nav>

src/core/templates/messages.html
{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		
			{% if message.tags %}
				{% if message.tags == "success" %}
					<div data-alert class="alert-box success radius">
				{% endif %}
				{% if message.tags == "warning" %}
					<div data-alert class="alert-box warning radius">
				{% endif %}
				{% if message.tags == "info" %}
					<div data-alert class="alert-box info radius">
				{% endif %}
				{% if message.tags == "error" %}
					<div data-alert class="alert-box alert radius">
				{% endif %}
			{% else %}
				<div data-alert class="alert-box secondary radius">
			{% endif %}
			{{ message }}
				<a href="#" class="close">&times;</a>
			</div>
		{% endfor %}
	</ul>
	</br></br>
{% endif %}