src/core/blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
	url(r'^(?P<post_slug>[a-z]+)/$', views.post, name='post'),
    url(r'^$', views.index, name='index'),
)

src/core/web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	url(r'^account/', include('gatekeeper.urls', namespace="gatekeeper")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'', include('pages.urls', namespace="pages")),
	
    # Application Specific definitions
    #url(r'^i/', include('personal.urls', namespace="personal")),	
)

src/core/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    post_slug = models.SlugField(max_length=80, help_text="This is the URL friendly Post name")
    post_name = models.CharField(max_length=50, help_text="Post Name")
    post_content = models.TextField(max_length=5000, help_text="Post content")
    post_created_date = models.DateTimeField(help_text="Date of creation of the Post")
    
    def __unicode__(self):
	    return self.post_name

class Comment(models.Model):
    comment_name = models.CharField(max_length=50, help_text="How would you like us to call you?")
    comment_email = models.EmailField(max_length=50, help_text="We promise not to publicize it")
    comment_web = models.URLField(max_length=50, blank=True, help_text="Your website URL")
    comment_details = models.TextField(max_length=500, help_text="Text in your comment")
    comment_created_date = models.DateTimeField(default=None, help_text="Date/Time of the post of this comment")
	
    def __unicode__(self):
	    return self.comment_details

src/core/blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post

def index(request):
    posts = Post.objects.order_by('post_created_date').reverse()[:10]
    context = {'posts': posts}
    return render(request, 'blog/index.html', context)
	
def post(request, post_slug):
    post = get_object_or_404(Post, post_slug=post_slug)
    return render(request, 'blog/post.html', {'post': post})

src/core/blog/templates/blog/index.html
{% extends "base-blog.html" %}

{% block blog_title %}
	Blog
{% endblock %}

{% block blog_name %}
	Blog
{% endblock %}

{% block blog_content %}
	{% if posts %}
		<ol>
		{% for post in posts %}
			<a href="{% url 'blog:post' post.post_slug %}">{{ post.post_name }}</a>
			</br>{{ post.post_created_date }}
			</br>{{ post.post_content|safe }}
			</br><hr></br>
		{% endfor %}
		</ol>
	{% else %}
		<p>No blog posts have been made as yet!</p>
	{% endif %}
{% endblock %}

src/core/blog/templates/blog/post.html
{% extends "base-blog.html" %}

{% block blog_title %}
	{{post.post_name}}
{% endblock %}

{% block blog_name %}
	<b>{{post.post_name}}</b>
{% endblock %}

{% block blog_content %}
	</br></br>
	<i>{{post.post_created_date}}</i>
	</br></br>
	{{post.post_content|safe}}
	</br></br>
	<a href="{% url 'blog:index' %}">back to blog...</a>
{% endblock %}